SQL> SELECT c.*, o.order_id, o.order_date, o.order_status, oi.product_id, oi.order_quantity, oi.order_unitprice FROM Customer c LEFT JOIN Orders o ON c.customer_id = o.customer_id LEFT JOIN Orderitems oi ON o.order_id = oi.order_id;

CUSTOMER_ID CUSTOMER_NAME             ADDRESS                                            CUSTOMER_PHONE  CUSTOMERCATEGORY_ID   ORDER_ID ORDER_DAT ORDER_STATUS              PRODUCT_ID ORDER_QUANTITY ORDER_UNITPRICE                                                                                       
----------- ------------------------- -------------------------------------------------- --------------- ------------------- ---------- --------- ------------------------- ---------- -------------- ---------------                                                                                       
          3 Paul Shah                 Kalanki                                            9815239872                        1          1 14-MAY-23 Shipped                            2              3             750                                                                                       
          2 Harry Smith               Baneshowr                                          9815235612                        3          2 19-JUN-23 Shipped                            9              1            2900                                                                                       
          5 Ram Lama                  Kakani                                             9817864572                        3          3 11-JAN-24 Pending                            1              1             150                                                                                       
          1 John Smith                Baluwatar                                          9812345612                        2          4 11-AUG-23 Shipped                            3              2            1150                                                                                       
          1 John Smith                Baluwatar                                          9812345612                        2          4 11-AUG-23 Shipped                            7              3              55                                                                                       
          5 Ram Lama                  Kakani                                             9817864572                        3          5 16-AUG-23 Shipped                            9              2            2900                                                                                       
          5 Ram Lama                  Kakani                                             9817864572                        3          6 29-AUG-23 Shipped                            2              1             750                                                                                       
          6 Aayush Singh              Putalisadak                                        9898767892                        2          7 29-MAR-23 Shipped                            5              2            1850                                                                                       
          6 Aayush Singh              Putalisadak                                        9898767892                        2          7 29-MAR-23 Shipped                            7              1            2200                                                                                       
          4 Sandeep Lama              Koteshwor                                          9814576872                        2          8 12-JAN-24 Pending                            4              5            1350                                                                                       
          3 Paul Shah                 Kalanki                                            9815239872                        1          1 14-MAY-23 Shipped                            9              1            2900                                                                                       
          7 Arijit Maharjan           Rani Pokhari                                       9683456782                        2                                                                                                                                                                                

12 rows selected.

SQL> spool off;
