SQL> SELECT TO_CHAR(TO_DATE(o.order_date, 'DD-Month-YYYY'), 'Month YYYY') AS month, SUM((oi.order_quantity * oi.order_unitprice) * (1 - cc.discountrate / 100)) AS total_revenue FROM Orders o JOIN Orderitems oi ON o.order_id = oi.order_id JOIN Customer c ON o.customer_id = c.customer_id JOIN Customercategory cc ON c.customercategory_id = cc.customercategory_id GROUP BY TO_CHAR(TO_DATE(o.order_date, 'DD-Month-YYYY'), 'Month YYYY') ORDER BY TO_CHAR(TO_DATE(o.order_date, 'DD-Month-YYYY'), 'Month YYYY');

MONTH                                     TOTAL_REVENUE                                                                                                                                                                                                                                                     
----------------------------------------- -------------                                                                                                                                                                                                                                                     
August    0023                                  8236.75                                                                                                                                                                                                                                                     
January   0024                                   6547.5                                                                                                                                                                                                                                                     
June      0023                                     2610                                                                                                                                                                                                                                                     
March     0023                                     5605                                                                                                                                                                                                                                                     
May       0023                                     5150                                                                                                                                                                                                                                                     

SQL> spool off;
