SQL> SELECT product_id, product_name, product_description, total_ordered_quantity FROM (SELECT p.product_id, p.product_name, p.product_description, SUM(oi.order_quantity) AS total_ordered_quantity, RANK() OVER (ORDER BY SUM(oi.order_quantity) DESC) AS rnk FROM Product p JOIN Orderitems oi ON p.product_id = oi.product_id GROUP BY p.product_id, p.product_name, p.product_description) WHERE rnk <= 3;

PRODUCT_ID PRODUCT_NAME              PRODUCT_DESCRIPTION                                TOTAL_ORDERED_QUANTITY                                                                                                                                                                                              
---------- ------------------------- -------------------------------------------------- ----------------------                                                                                                                                                                                              
         4 GL65                      Gaming Laptop                                                           5                                                                                                                                                                                              
         9 Samsung OLED TV           70 inch 8K OLED TV                                                      4                                                                                                                                                                                              
         7 M1 Pro                    Apple MacBook                                                           4                                                                                                                                                                                              
         2 Totan 2020 Series         Gaming Chair                                                            4                                                                                                                                                                                              

SQL> spool off;
